class LocalizationService {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'ComMobi-Tracker',
      'facilitator_profile': 'Facilitator Profile',
      'name': 'Name',
      'region': 'Region',
      'district': 'District/Mora',
      'home': 'Home',
      'my_families': 'My Families',
      'group_sessions': 'Community Support Groups (GSP)',
      'emergency_alerts': 'Emergency Safeguarding Alert',
      'sync_status': 'Synchronization Status',
      'sync_pending': '{} forms pending synchronization',
      'sync_success': 'Synchronization successful!',
      'sync_failed': 'Synchronization failed. Saved offline.',
      'sync_in_progress': 'Synchronizing...',
      'sync_button': 'SYNCHRONIZE DATA',
      'search_placeholder': 'Search by name or neighborhood...',
      'new_family': '+ New Family',
      'children': 'Children',
      'last_visit': 'Last Visit',
      'status_full': 'Full Follow-up',
      'status_partial': 'Partial Follow-up',
      'add_new_family_title': 'Add New Family',
      'household_name': 'Household Head Name',
      'neighborhood_label': 'Neighborhood / Quarter',
      'children_count': 'Number of Children',
      'cancel': 'Cancel',
      'save_offline': 'SAVE (OFFLINE)',
      'module_title': 'Facilitator\'s Guide: 10 Modules',
      'module_1': 'Module 1: Rights & Birth Registration',
      'birth_cert_q': 'Does the child have a birth certificate?',
      'disability_q': 'Any children with disabilities?',
      'module_2': 'Module 2: Community Role & Best Interests',
      'best_interest_q': 'Child\'s best interests and community rights respected?',
      'module_3_4': 'Modules 3 & 4: First 1,000 Days & WASH',
      'vaccination_q': 'Vaccinations up-to-date?',
      'breastfeeding_q': 'Exclusive breastfeeding practiced?',
      'bednets_q': 'Bed nets used by children?',
      'wash_q': 'Handwashing with soap practiced?',
      'module_5': 'Module 5: Family Financial Budgeting',
      'budgeting_q': 'Practicing family financial budgeting?',
      'module_6_10': 'Modules 6-10: Positive Discipline & Communication',
      'abuse_q': 'Any corporal punishment or verbal abuse used this month?',
      'dialogue_q': 'Use of active dialogue / positive reinforcement?',
      'visit_notes': 'Voice or Text Visit Notes',
      'notes_placeholder': 'Key comments on family progress...',
      'save_success': 'Record saved locally!',
      'report_title': 'Community Support Group Session Report',
      'date': 'Date',
      'location': 'Location (e.g., Chief\'s Palace, Church, Mosque)',
      'men_count': 'Men Attendance',
      'women_count': 'Women Attendance',
      'topic_covered': 'Topic Covered',
      'masculinity_index': 'Positive Masculinity Index',
      'masculinity_desc': '% of male attendance in the workshop',
      'alert_title': 'Confidential Safeguarding & Emergency Alert',
      'risk_category': 'Risk Category',
      'risk_physical_abuse': 'Risk of Physical Abuse',
      'risk_marriage': 'Child Marriage Risk',
      'risk_neglect': 'Severe Neglect',
      'risk_sexual': 'Sexual Exploitation',
      'description_label': 'Anonymized Incident Description (Do not write names)',
      'report_urgent': 'REPORT URGENT CASE',
      'emergency_flag': 'High Priority Emergency Alert',
      'tts_activated': 'Text-to-speech activated',
      'tts_deactivated': 'Text-to-speech deactivated',
      'toggle_contrast': 'Toggle High Contrast Dark Theme',
      'toggle_lang': 'Change Language',
      'statistics': 'Statistics',
    },
    'fr': {
      'app_name': 'ComMobi-Tracker',
      'facilitator_profile': 'Profil du Facilitateur',
      'name': 'Nom',
      'region': 'Région',
      'district': 'District/Mora',
      'home': 'Accueil',
      'my_families': 'Mes Familles',
      'group_sessions': 'Groupes de Soutien Communautaire (GSP)',
      'emergency_alerts': 'Alerte d\'Urgence de Sauvegarde',
      'sync_status': 'Statut de Synchronisation',
      'sync_pending': '{} formulaires en attente de synchronisation',
      'sync_success': 'Synchronisation réussie !',
      'sync_failed': 'Échec de synchronisation. Enregistré hors ligne.',
      'sync_in_progress': 'Synchronisation en cours...',
      'sync_button': 'SYNCHRONISER LES DONNÉES',
      'search_placeholder': 'Rechercher par nom ou quartier...',
      'new_family': '+ Nouvelle Famille',
      'children': 'Enfants',
      'last_visit': 'Dernière Visite',
      'status_full': 'Suivi Complet',
      'status_partial': 'Suivi Partiel',
      'add_new_family_title': 'Ajouter une Nouvelle Famille',
      'household_name': 'Nom du chef de ménage',
      'neighborhood_label': 'Quartier / Village',
      'children_count': 'Nombre d\'enfants',
      'cancel': 'Annuler',
      'save_offline': 'ENREGISTRER (HORS LIGNE)',
      'module_title': 'Guide de Facilitation : 10 Modules',
      'module_1': 'Module 1 : Droits & Enregistrement des Naissances',
      'birth_cert_q': 'L\'enfant a-t-il un acte de naissance ?',
      'disability_q': 'Y a-t-il des enfants vivant avec un handicap ?',
      'module_2': 'Module 2 : Rôle Communautaire & Intérêt Supérieur',
      'best_interest_q': 'Intérêts supérieurs de l\'enfant et droits respectés ?',
      'module_3_4': 'Modules 3 & 4 : 1 000 Premiers Jours & WASH',
      'vaccination_q': 'Vaccinations à jour ?',
      'breastfeeding_q': 'Allaitement maternel exclusif pratiqué ?',
      'bednets_q': 'Moustiquaires imprégnées utilisées par les enfants ?',
      'wash_q': 'Lavage des mains avec du savon pratiqué ?',
      'module_5': 'Module 5 : Budget Familial',
      'budgeting_q': 'Pratique de la budgétisation financière familiale ?',
      'module_6_10': 'Modules 6-10 : Discipline Positive & Communication',
      'abuse_q': 'Utilisation de punition corporelle ou violence verbale ce mois ?',
      'dialogue_q': 'Recours au dialogue actif / renforcement positif ?',
      'visit_notes': 'Notes de Visite (Vocale ou Texte)',
      'notes_placeholder': 'Remarques clés sur les progrès de la famille...',
      'save_success': 'Fiche enregistrée localement !',
      'report_title': 'Rapport de Session du Groupe Communautaire',
      'date': 'Date',
      'location': 'Lieu (ex: Chefferie, Église, Mosquée)',
      'men_count': 'Nombre d\'Hommes',
      'women_count': 'Nombre de Femmes',
      'topic_covered': 'Sujet Abordé',
      'masculinity_index': 'Indice de Masculinité Absolute/Positive',
      'masculinity_desc': '% de participation des hommes à l\'atelier',
      'alert_title': 'Signalement Confidentiel et Médical d\'Urgence',
      'risk_category': 'Catégorie de Risque',
      'risk_physical_abuse': 'Risque d\'Abus Physique',
      'risk_marriage': 'Risque de Mariage d\'Enfants',
      'risk_neglect': 'Négligence Grave',
      'risk_sexual': 'Exploitation Sexuelle',
      'description_label': 'Description de l\'incident anonymisée (Pas de nom)',
      'report_urgent': 'SIGNALER LE CAS URGENT',
      'emergency_flag': 'Alerte d\'Urgence Priorité Rouge',
      'tts_activated': 'Synthèse vocale activée',
      'tts_deactivated': 'Synthèse vocale désactivée',
      'toggle_contrast': 'Activer le Thème Sombre Contraste Élevé',
      'toggle_lang': 'Changer de Langue',
      'statistics': 'Statistiques',
    },
    'pcm': {
      'app_name': 'ComMobi-Tracker',
      'facilitator_profile': 'Facilitator Profile',
      'name': 'Name',
      'region': 'Region',
      'district': 'District/Mora',
      'home': 'Home',
      'my_families': 'Ma Family Dem',
      'group_sessions': 'Community Support Groups (GSP)',
      'emergency_alerts': 'Safeguarding Emergency Alert',
      'sync_status': 'Sync Status',
      'sync_pending': '{} paper dem write wait for sync',
      'sync_success': 'Information sync fine structure!',
      'sync_failed': 'Network weak. Information save inside machine.',
      'sync_in_progress': 'Information de go for web...',
      'sync_button': 'SEND DATA FOR NET',
      'search_placeholder': 'Find family by name or quarter...',
      'new_family': '+ Add New Family',
      'children': 'Pikin dem',
      'last_visit': 'Last Day for Visit',
      'status_full': 'Full Follow-up',
      'status_partial': 'Small Follow-up',
      'add_new_family_title': 'Write New Family Info',
      'household_name': 'Head of House Name',
      'neighborhood_label': 'Quarter / Village',
      'children_count': 'How many pikin dey for house?',
      'cancel': 'Cancel',
      'save_offline': 'SAVE FOR LOCAL (OFFLINE)',
      'module_title': 'Guide Book: 10 Modules',
      'module_1': 'Module 1: Pikin Right & Born Book',
      'birth_cert_q': 'Pikin get born-certificate?',
      'disability_q': 'Any pikin get disability?',
      'module_2': 'Module 2: Community Role & Pikin Benefit',
      'best_interest_q': 'Pikin interest dey priority for community?',
      'module_3_4': 'Modules 3 & 4: Early Years & WASH',
      'vaccination_q': 'Pikin complete injection dem?',
      'breastfeeding_q': 'Only breastmilk pikin chop first 6 months?',
      'bednets_q': 'Pikin sleep under net?',
      'wash_q': 'Washing hand with water and soap?',
      'module_5': 'Module 5: Family Money Matter',
      'budgeting_q': 'Family dey plan money write down?',
      'module_6_10': 'Modules 6-10: Fine Training & Communication',
      'abuse_q': 'They beat or shout pikin this month?',
      'dialogue_q': 'Talking fine and encourage pikin?',
      'visit_notes': 'Talk or Write Note for Visit',
      'notes_placeholder': 'Write important updates for the family...',
      'save_success': 'Saved for inside phone fine!',
      'report_title': 'GSP Meeting Report Info',
      'date': 'Date',
      'location': 'Meeting Place (e.g. Chief Palace, Church, Mosque)',
      'men_count': 'Men Number',
      'women_count': 'Women Number',
      'topic_covered': 'Sujet wey we look',
      'masculinity_index': 'Positive Masculinity Index',
      'masculinity_desc': '% of man participation for meeting',
      'alert_title': 'Confidential Safekeeping & Emergency Alert',
      'risk_category': 'Worry Category',
      'risk_physical_abuse': 'Risk of beating/abuse',
      'risk_marriage': 'Early Marriage Risk',
      'risk_neglect': 'No take care of pikin',
      'risk_sexual': 'Sexual Exploitation',
      'description_label': 'Describe wetin happen (no put person name)',
      'report_urgent': 'REPORT FOR URGENT STATUS',
      'emergency_flag': 'High Priority Red Alert',
      'tts_activated': 'Talk machines activated',
      'tts_deactivated': 'Talk machines deactivated',
      'toggle_contrast': 'Change for High Contrast Dark View',
      'toggle_lang': 'Change Language',
      'statistics': 'Statistics',
    }
  };

  static String translate(String key, String locale, {List<String>? args}) {
    final Map<String, String>? localeValues = _localizedValues[locale] ?? _localizedValues['en'];
    String value = localeValues?[key] ?? _localizedValues['en']?[key] ?? key;

    if (args != null && args.isNotEmpty) {
      for (var arg in args) {
        value = value.replaceFirst('{}', arg);
      }
    }
    return value;
  }
}
